-- Seed data for Module 7: 10 posts with 5 comments each
-- Designed to clearly exhibit the N+1 problem (11 queries vs 1 or 2)

INSERT INTO blog_post (title, body) VALUES
('Why N+1 matters',                 'Lazy associations and the trap of iteration.'),
('Connection pooling 101',          'A practical look at HikariCP tuning.'),
('Optimistic vs pessimistic locks', 'Knowing which to reach for.'),
('Understanding @Transactional',    'Common pitfalls in Spring transactions.'),
('Native queries in Hibernate',     'When JPQL is not enough.'),
('Caching at the right layer',      'First-level, second-level, and beyond.'),
('Indexes and query plans',         'Read the plan before you tune.'),
('Keyset pagination explained',     'Why offset breaks at scale.'),
('Specifications and dynamic queries','Composing predicates conditionally.'),
('JOIN FETCH and EntityGraph',      'Two tools, slightly different jobs.');

-- 5 comments per post (50 total)
INSERT INTO comment (post_id, author, body) VALUES
(1, 'Liam',   'Great explanation, thanks.'),
(1, 'Aisha',  'I had this exact problem last week.'),
(1, 'Noah',   'Saved my afternoon.'),
(1, 'Mei',    'Bookmarking this.'),
(1, 'Oliver', 'Worth re-reading once a quarter.'),
(2, 'Emma',   'Could you cover pool sizing in a follow-up?'),
(2, 'Zara',   'The defaults are rarely right.'),
(2, 'Lucas',  'leakDetectionThreshold is underused.'),
(2, 'Hana',   'Combine with prepared statement caching.'),
(2, 'Amir',   'Solid intro.'),
(3, 'Liam',   'Optimistic for normal updates, pessimistic for contention.'),
(3, 'Aisha',  'Retry with backoff is non-negotiable.'),
(3, 'Noah',   'PostgreSQL FOR NO KEY UPDATE caught me out.'),
(3, 'Mei',    'Good explanation.'),
(3, 'Oliver', 'Add a section on deadlocks?'),
(4, 'Emma',   'Self-invocation is the most common gotcha.'),
(4, 'Zara',   'Proxy boundaries are invisible until they bite.'),
(4, 'Lucas',  'Use TransactionSynchronizationManager to verify.'),
(4, 'Hana',   'Spot on.'),
(4, 'Amir',   'Helpful.'),
(5, 'Liam',   'Constructor projections changed my life.'),
(5, 'Aisha',  '@SqlResultSetMapping is verbose but powerful.'),
(5, 'Noah',   'Worth showing both interface and class projections.'),
(5, 'Mei',    'Useful examples.'),
(5, 'Oliver', 'Cite the dialect carefully.'),
(6, 'Emma',   'L1 vs L2 confusion is real.'),
(6, 'Zara',   'Ehcache works well, Caffeine is even simpler.'),
(6, 'Lucas',  'TTL choices matter more than people think.'),
(6, 'Hana',   'Concurrent strategy matters too.'),
(6, 'Amir',   'Useful.'),
(7, 'Liam',   'EXPLAIN ANALYZE before tuning anything.'),
(7, 'Aisha',  'Composite indexes are an art.'),
(7, 'Noah',   'Sequential scan is sometimes correct.'),
(7, 'Mei',    'Great tip.'),
(7, 'Oliver', 'Add coverage of pg_stat_statements.'),
(8, 'Emma',   'Offset hurts past page 100 or so.'),
(8, 'Zara',   'Tiebreaker columns matter.'),
(8, 'Lucas',  'Keyset works best with monotonic columns.'),
(8, 'Hana',   'Cursor pagination is the GraphQL flavor.'),
(8, 'Amir',   'Useful.'),
(9, 'Liam',   'Predicate.where chaining is elegant.'),
(9, 'Aisha',  'Combine with projections for narrow reads.'),
(9, 'Noah',   'Specifications + paging is the sweet spot.'),
(9, 'Mei',    'Good.'),
(9, 'Oliver', 'Don''t over-abstract.'),
(10, 'Emma',  'JOIN FETCH for the common case.'),
(10, 'Zara',  'EntityGraph for reusable shapes.'),
(10, 'Lucas', 'Both with DISTINCT to avoid duplicates.'),
(10, 'Hana',  'Solid summary.'),
(10, 'Amir',  'Good post.');